# Use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION

language: scala

scala:
  - 2.11.6
  - 2.10.5

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm