language: scala

scala:
  - 2.11.6
  - 2.10.5

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk6
  - openjdk7

script: sbt ++$TRAVIS_SCALA_VERSION test

notifications:
  email:
    recipients:
      - jfklingler@gmail.com